# Generated by Django 4.0.6 on 2022-08-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
